apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-5vqd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-5vqd
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-5vqd
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-5vqd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-5vqd
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xtjg-tenant/rhtap-demo-app/hacbs-test-project-5vqd@sha256:4b9c09a70d16cba6b580c3154e560a0a62073608ab28ea3118dcbc5863298f34
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
