apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-5vqd
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xtjg-tenant/rhtap-demo-app/hacbs-test-project-5vqd@sha256:4b9c09a70d16cba6b580c3154e560a0a62073608ab28ea3118dcbc5863298f34
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
